### PR TITLE
Add enums for some fields

### PR DESCRIPTION
**Pull request by BalderHolst**
This PR adds enums for entity `direction` and arithmetic combinator operations and decider combinator comparisons. Let me know if there is any problematic parts of the code.

### CODE REVIEW

**Review by coriolinus — COMMENTED** [review]
Looks good, pending CI. Out of curiosity: why implement `Display` but not `FromStr`? In general there's a symmetry between those two traits.

**Comment by coriolinus** [comment]
Of course, all existing tests must pass before I can consider merging.

**Comment by BalderHolst** [comment]
Hello again, I have fixed the major parsing errors for the combinator operation enums and those pass the tests now. I have also removed the `Display` implementation. I was using is in my own project, but they did not correspond to how the operations are serialized, and it was hard to find differing representation for XOR (^) and exponentiation (^).

I am, however, having a hard time getting the `Direction` to pass the round trip test. Before my change the field was an `Option<U8>` which stores information about whether the field was specified by the blueprint or not. My change turned the field into `Direction` which does not stores this information. I have made the serializer skip this field if it is the default (North), but this breaks the `super_compact_tileable_mining.txt` round trip test, as some of the entities have their direction explicitly set to `North`, which is then stripped out when reserializing the blueprint.

Do you have a good idea to fix this or would you rather this field be `Option<Direction>`? I personally think a plain `Direction` is much nicer, but I cannot figure out how to make the test pass then.

**Comment by coriolinus** [comment]
Why not `Option<Direction>`? That seems to be semantically what you want anyway.

**Comment by BalderHolst** [comment]
I cannot think of a use case where you would want the option to be able to serialize `Direction::North` instead of just skipping it in serialization. To me (as a user) `Some(Direction::North)` has the same meaning as `None`, which may not be entirely clear. It also creates a prettier match statement, when trying to handle all possible directions :).

`Option<Direction>` is also fine by me, but I think a plain `Direction` would be neat.

**Comment by coriolinus** [comment]
The challenge here is not to come up with an ideal representative model of the blueprint state. It is instead to accurately model what the game does. It sure sounds like the game is using something like `Option<Direction>`, so that's what we should do.

**Comment by coriolinus** [comment]
As for the match statement:

```rust
match direction.unwrap_or_default() 
```

**Comment by BalderHolst** [comment]
Alright, i see. I have changed it to `Option<Direction>`. All tests are passing on my end.

**Pull request merged**
